# Generated by Django 3.2.18 on 2023-06-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
